# Generated by Django 5.0.7 on 2024-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='pharmacy',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
