# Generated by Django 5.0.7 on 2024-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='day_of_week',
            field=models.CharField(max_length=255),
        ),
    ]
