# Generated by Django 5.0.7 on 2024-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_app', '0002_alter_purchasehistory_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
