# Generated by Django 5.0.7 on 2024-08-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_app', '0004_alter_mask_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='pharmacy',
            field=models.CharField(max_length=255),
        ),
    ]
